# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Cong's Blog
tagline:          Personal Blog of Cong Ding
description:      "Random thoughts since 03/19/2019"
url:              https://congding.info/blog/
baseurl:          /blog/
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

author:
  name:           Cong Ding
  url:            https://congding.info/

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            2.0.1

github:
  repo:             https://github.com/tson1111/blog
